name: Build and Release

on:
  push:
    tags:
      - "*"   # 任何 tag push 都会触发

permissions:
  contents: write   # 必须有写权限才能创建 Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build (normal mode)
        run: bunx esbuild src/index.ts --bundle --platform=node --outfile=dist/index.js

      - name: Build (release mode)
        run: bunx esbuild src/index.ts --bundle --platform=node --minify --outfile=dist/index.min.js

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}   # 当前推送的 tag
          name: Release ${{ github.ref_name }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}