name: Build and Release

on:
  push:
    branches:
      - "**"   # 任意分支推送都触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build (normal mode)
        run: bunx esbuild src/index.ts --bundle --platform=node --outfile=dist/index.js

      - name: Build (release mode)
        run: bunx esbuild src/index.ts --bundle --platform=node --minify --outfile=dist/index.min.js

      - name: Archive build artifacts
        run: |
          mkdir artifacts
          cp dist/index.js artifacts/
          cp dist/index.min.js artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}